steps:
# Step 1: Install dependencies (optional, can be handled in Dockerfile)
- name: 'node:16'
  entrypoint: 'npm'
  args: ['install']

# Step 2: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/react-cicd', '.']

# Step 3: Push the image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/react-cicd']

# Step 4: Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - 'run'
  - 'deploy'
  - 'react-cicd-service'
  - '--image'
  - 'gcr.io/$PROJECT_ID/react-cicd'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  entrypoint: 'gcloud'

options:
  logging: CLOUD_LOGGING_ONLY
timeout: '1200s'